baseURL = ''
languageCode = 'pt-br'
title = 'Unidade Força'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = 'Início'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'História'
    url = '/historia/'
    weight = 2
  [[menu.main]]
    name = 'Membros'
    url = '/membros/'
    weight = 3
